<?php

// This is an autogenerated file - do not edit!

// @codeCoverageIgnoreStart
spl_autoload_register(
    function($class)
    {
        static $classes = array(
            'spriebsch\\hashmap\\exception' => '/Exception.php',
            'spriebsch\\hashmap\\hashmap' => '/HashMap.php',
            'spriebsch\\hashmap\\diff' => '/Diff.php'
       );
       $cn = strtolower($class);
       if (isset($classes[$cn])) {
        require __DIR__ . $classes[$cn];
       }
    }
);
// @codeCoverageIgnoreEnd
